Implemented spacetime deletion
csmberkeley/csm_web pull request #299
Opened 2022-08-01 00:26 UTC by edwardneo

2022-08-21 07:03 UTC, smartspot2 requested changes
Overall, this looks really good; most of my comments are for smaller things/stylistic things, but I'll summarize a few points here.

For the frontend, there's mostly just naming convention nitpicks, and some styling changes (ex. spacing, alignment); beyond that, the functionality for the UI looks great.

For the backend, the main things I commented on are to add logging and error messages, which are also just small nitpicks. Additionally (and more importantly), I don't see any tests currently, and I'd strongly suggest adding tests before deploying, to ensure that all edge cases are handled correctly (especially with timing in deleting spacetimes and overrides).

Lastly, I'd recommend changing this PR to a non-draft PR when you push your next changes, and I'd also recommend changing the title and description of the PR to be something more descriptive for this project. That is, add a few sentences/bullet points describing exactly what this project is, and an overall list of things changed through this pull request.

Keep up the good work!

2022-08-21 07:03 UTC, smartspot2 commented on csm_web/frontend/src/components/section/SpacetimeEditModal.tsx
> +      override: props.overrideEdit,
I don't believe there is any need to make this a state; this variable won't be changing in the lifecycle of the component, and is always going to be the same as the prop.

2022-08-21 07:03 UTC, smartspot2 commented on csm_web/frontend/src/components/section/SpacetimeEditModal.tsx
> +  overrideEdit: boolean;
[nit] imo, `isEditingOverride` or `editingOverride` seems more intuitively a boolean; this is incredibly tiny, so feel free to ignore if you feel differently.

2022-08-31 02:16 UTC, noortor requested changes

2022-08-31 02:16 UTC, noortor commented on csm_web/frontend/src/components/section/SpacetimeDelete.tsx
> +  }
replace function calls with ternary operators `{overrideDelete ? "Override": "Spacetime"}`

2022-09-09 00:13 UTC, smartspot2 commented
@kennethsieu @edwardneo Is there any update on this PR? The last changes were from 8 days ago.

2022-09-13 02:47 UTC, noortor approved these changes

2022-09-13 02:54 UTC, smartspot2 approved these changes

2022-09-13 03:01 UTC, merged