Fix multiple mentors added to matcher
csmberkeley/csm_web pull request #438
Opened 2023-09-04 06:12 UTC by ericyche

Matcher would create multiple mentors with the same user. We turn the input list into a set so there cannot be any duplicate emails. 
<img width="829" alt="Screenshot 2023-09-03 at 11 11 19 PM" src="https://github.com/csmberkeley/csm_web/assets/62233299/d945ec92-f1fd-4c40-8cd0-cb96f1c3359a">
<img width="1040" alt="Screenshot 2023-09-03 at 11 10 57 PM" src="https://github.com/csmberkeley/csm_web/assets/62233299/5ba1bfe7-5bc2-48f4-a3da-7d3fca800f11">

2023-09-04 06:17 UTC, ericyche commented
i am never safe from pre-commit

2023-09-07 07:50 UTC, smartspot2 requested changes
Fix the one variable name and I'll approve the next revision.

2023-09-07 07:50 UTC, smartspot2 commented on csm_web/scheduler/views/matcher.py
> -    preferences = MatcherPreference.objects.filter(slot__matcher=course.matcher)
This should be `matcher_preferences` (plural) to match the other variables (and the semantics of this variable)

2023-09-08 04:11 UTC, ericyche reviewed
idk what this page is on github but i will add a comment.

2023-09-08 21:35 UTC, smartspot2 requested changes
Please squash and remove the merge commit.

2023-09-08 22:22 UTC, ericyche commented
not fan of merge commit :(

2023-09-09 05:15 UTC, edwardneo approved these changes
Nice!

2023-09-09 05:47 UTC, smartspot2 approved these changes

2023-09-09 17:58 UTC, merged