Restyle matcher UI
csmberkeley/csm_web pull request #470
Opened 2024-03-04 01:42 UTC by smartspot2

This PR makes various miscellaneous improvements to the matcher UI.

Coordinators have created slots without knowing that many slots are actually linked; a confirmation modal has been added because of this, listing out all of the slots along with a count of the number of slots to submit.

Another confirmation modal was added to the button opening the preference form for mentors, making it clear that slots cannot be edited afterward. This can probably be reverted or changed if in the future we decide to rework the slot creation system to allow for slot edits.

Further, there were many matcher button and input styles that are not consistent with the rest of the site; these classes have also been migrated over.

Closes #437.

2024-03-07 05:34 UTC, jacovkim approved these changes
Looks good to me!

2024-03-07 05:48 UTC, edwardneo requested changes
Looks generally good -- why is there a save button and a submit button for creating the matcher slots, and you can hit submit without saving? It seems a bit weird to me, and I think coordinators will accidentally forget to save a slot they wanted to save but submit it anyways.

2024-03-14 04:24 UTC, edwardneo approved these changes
LGTM!

2024-03-14 04:26 UTC, jacovkim approved these changes
LGTM!

2024-03-14 04:28 UTC, merged